# Numpy Study 9-10-19
Based on https://www.youtube.com/watch?v=GB9ByFAIAH4

In [1]:
import numpy as np

## Basics

In [2]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [3]:
b = np.array([[9.1,8.0,7.0],[6.0,5.2,4.0]])
print (b)

[[9.1 8.  7. ]
 [6.  5.2 4. ]]


In [4]:
# Get Dimensions
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
# Int 32 take up 4 bytes (1 byte = 8 bits per character, 32/8 = 4 bytes)
a.dtype

dtype('int32')

In [7]:
# Get Size (itemsize = size per element, size = number of elements)
print(a.itemsize)
print(a.size)

4
3


In [8]:
# Change data type of array to have a smaller value
a = np.array([1,2,3], dtype='int16')

In [9]:
a.dtype

dtype('int16')

In [10]:
# Get Size
a.itemsize

2

In [11]:
#Get Total Size ( number of elements times size per element = bytes)
a.size * a.itemsize

6

In [12]:
#Direct number of bytes
a.nbytes

6

In [13]:
# b are floats and have a larger size than integers
b.nbytes

48

## Accessing / Changing specific elements, rows, columns, etc.

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a.shape

(2, 7)

In [16]:
#Get specific element [r,c] (0 to 6)
print(a[1,5])
print(a[1,-2])

13
13


In [17]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [19]:
# Getting specific elements [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [20]:
# changing elements
a[1,5] = 20
print (a)

a[:,2] = 5
print (a)

a[:,2] = [99,100]
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[  1   2  99   4   5   6   7]
 [  8   9 100  11  12  20  14]]


In [21]:
# 3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# get element from 3d (work outside in)
b[0,1,1]

4

In [23]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [24]:
# change element (should be the same dimension)
b[:,1,:] = [[111,222],[888,999]]
b

array([[[  1,   2],
        [111, 222]],

       [[  5,   6],
        [888, 999]]])

## Initialize n Different Types of Arrays

In [25]:
# All 0s Matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [29]:
# All 1s matrix
np.ones((4,3,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [30]:
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [31]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
# Random Decimal Numbers
np.random.rand(4,2,3)

array([[[0.76344739, 0.35874039, 0.04914788],
        [0.661393  , 0.85932481, 0.54923251]],

       [[0.66492647, 0.89544887, 0.59013996],
        [0.46384923, 0.37262485, 0.78740719]],

       [[0.39479908, 0.96091275, 0.57942355],
        [0.25392039, 0.65572846, 0.98517481]],

       [[0.12558099, 0.01926656, 0.57010239],
        [0.07230227, 0.59403575, 0.8861677 ]]])

In [33]:
np.random.random_sample(a.shape)

array([[0.48405432, 0.97195366, 0.38798419, 0.45901015, 0.46389012,
        0.86591756, 0.47597543],
       [0.83743612, 0.83131045, 0.51929195, 0.97184302, 0.84211639,
        0.39540747, 0.41545564]])

In [34]:
# Random Integer Values
np.random.randint(7, size=(3,3))

array([[1, 5, 3],
       [5, 2, 2],
       [2, 2, 6]])

In [35]:
np.random.randint(4, size=(3,3))

array([[2, 1, 2],
       [1, 3, 0],
       [2, 1, 0]])

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis =0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [38]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [39]:
# My Solution to the test
test = np.ones((5,5), dtype = "int16")
test[1:4,1:4] = np.zeros((3,3))
test[2,2] = 9
test
# My solution is shorter than one line

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [40]:
#Instructor's Solution to the test
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Be Careful when copying arrays!!!

In [41]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [42]:
b = a
b

array([1, 2, 3])

In [43]:
b[0] = 100
b

array([100,   2,   3])

In [44]:
# If you print a; it will have 100 on element 0 instead of 1
a

array([100,   2,   3])

In [45]:
# use .copy() to copy an array instead of just equal
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print (a)
print (b)

[1 2 3]
[100   2   3]


## Mathematics

In [46]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [47]:
a + 2

array([3, 4, 5, 6])

In [48]:
a - 2

array([-1,  0,  1,  2])

In [49]:
a * 2

array([2, 4, 6, 8])

In [50]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [51]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [52]:
# a to the 2nd power
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [53]:
# square root of a
a ** 1/2

array([0.5, 1. , 1.5, 2. ])

In [54]:
# Sine of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [55]:
# for other functions https://docs.scipy.org/doc/numpy/reference/routines.math.html

## Linear Algebra

In [57]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [58]:
# 1st row x 1st column of the 2nd matrix, 1st row x 2nd column - upper right, 
# 2nd row x 1st column - lower left, 2nd row x 2nd column - lower right

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# find np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

## Statistics

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats)

1

In [62]:
np.max(stats)

6

In [68]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [69]:
np.max(stats, axis = 1)

array([3, 6])

In [70]:
# sum all elements
np.sum(stats)

21

In [71]:
# sum elements downwards
np.sum(stats, axis = 0)

array([5, 7, 9])

## Reorganizing Arrays